// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKL_PECiJVqfO1vZ2RHDcuOSZPolivArs',
    appId: '1:224576759441:web:991b5290a3f5de913dc130',
    messagingSenderId: '224576759441',
    projectId: 'zuno-69127',
    authDomain: 'zuno-69127.firebaseapp.com',
    storageBucket: 'zuno-69127.firebasestorage.app',
    measurementId: 'G-QX6DKQYY48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGg7-4QYrRxFS_mEyCMOhtlNEXXP3Fkpg',
    appId: '1:224576759441:android:736d40905063edef3dc130',
    messagingSenderId: '224576759441',
    projectId: 'zuno-69127',
    storageBucket: 'zuno-69127.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDpIKEqqeCYDOrdm-luec_jrph8KYgArI',
    appId: '1:224576759441:ios:5309d69f87fe35ea3dc130',
    messagingSenderId: '224576759441',
    projectId: 'zuno-69127',
    storageBucket: 'zuno-69127.firebasestorage.app',
    iosBundleId: 'com.example.helloWorld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDpIKEqqeCYDOrdm-luec_jrph8KYgArI',
    appId: '1:224576759441:ios:5309d69f87fe35ea3dc130',
    messagingSenderId: '224576759441',
    projectId: 'zuno-69127',
    storageBucket: 'zuno-69127.firebasestorage.app',
    iosBundleId: 'com.example.helloWorld',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKL_PECiJVqfO1vZ2RHDcuOSZPolivArs',
    appId: '1:224576759441:web:406b8bc87f28b0313dc130',
    messagingSenderId: '224576759441',
    projectId: 'zuno-69127',
    authDomain: 'zuno-69127.firebaseapp.com',
    storageBucket: 'zuno-69127.firebasestorage.app',
    measurementId: 'G-LX9F7Z5P69',
  );
}
